create table FILES (
    NO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar2 (100) NOT NULL,
    name varchar2(100) NOT NULL,
    oName varchar2(200) NOT NULL,
    sName varchar2(200) NOT NULL,
    rdate date
);