select ename, INITCAP(ENAME) "INITCAP"
    FROM EMP
    WHERE DEPTNO = 10;
SELECT COUNT(*), COUNT(COMM)
FROM EMP;

SELECT S.NAME "STU_NUME", P.NAME "PROF_NAME"
FROM STUDENT S, PROFESSOR P
WHERE S.PROFNO = P.PROFNO(+);

SELECT EMPNO, ENAME, MGR FROM EMP;

SELECT E1.ENAME "ENAME", E2.ENAME "MGR_ENAME"
FROM EMP E1, EMP E2
WHERE E1.MGR = E2.EMPNO;