--실습 1-1
ALTER SESSION SET "_ORACLE_SCRIPT" = true;
CREATE USER shop IDENTIFIED BY 1234;
GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO shop;
exit;

--실습 1-2
create table Customer (
    CID VARCHAR2(20) primary key,
    name VARCHAR2(20) NOT NULL,
    hp CHAR(13) unique,
    address VARCHAR2(200),
    RDATE DATE NOT NULL
);

CREATE table Product (
    pno number(4) primary key,
    pname varchar2(30) not null,
    stock number default 0,
    price number ,
    company varchar2(20)
);

create table Orders (
    ORD_NO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ORD_CID VARCHAR2(20) NOT NULL,
    ORD_PNO NUMBER(4) NOT NULL,
    ORD_CNT NUMBER DEFAULT 1,
    ORD_DATE DATE NOT NULL
);
    
--실습 1-3
insert into Customer values ('c101','김유신','010-1234-1001','김해시 봉황동','2022-01-01');
insert into Customer values ('c102','김춘추','010-1234-1002','경주시 보문동','2022-01-02');
insert into Customer values ('c103','장보고','010-1234-1003','완도군 청산면','2022-01-03');
insert into Customer values ('c104','강감찬','010-1234-1004','서울시 마포구','2022-01-04');
insert into Customer values ('c105','이성계',null,null,'2022-01-05');
insert into Customer values ('c106','정철','010-1234-1006','경기도 용인시','2022-01-06');
insert into Customer values ('c107','허준',null,null,'2022-01-07');
insert into Customer values ('c108','이순신','010-1234-1008','서울시 영등포구','2022-01-08');
insert into Customer values ('c109','송상현','010-1234-1009','부산시 동래구','2022-01-09');
insert into Customer values ('c110','정약용','010-1234-1010','경기도 광주시','2022-01-10');

insert into Product values (1,'새우깡',5000,1500,'농심');
insert into Product values (2,'초코파이',2500,2500,'오리온');
insert into Product values (3,'포카칩',3600,1700,'오리온');
insert into Product values (4,'양파링',1250,1800,'농심');
insert into Product values (5,'죠리퐁',2200,null,'크라운');
insert into Product values (6,'마가렛트',3500,3500,'롯데');
insert into Product values (7,'뿌셔뿌셔',1650,1200,'오뚜기');

insert into ORDERS VALUES (1,'c102',3,2,'2022-07-01 12:15:10');
insert into ORDERS VALUES (2,'c101',4,1,'2022-07-01 14:16:11');
insert into ORDERS VALUES (3,'c108',1,1,'2022-07-01 17:23:18');
insert into ORDERS VALUES (4,'c109',6,5,'2022-07-02 10:46:36');
insert into ORDERS VALUES (5,'c102',2,1,'2022-07-03 09:15:37');
insert into ORDERS VALUES (6,'c101',7,3,'2022-07-03 12:35:12');
insert into ORDERS VALUES (7,'c110',1,2,'2022-07-03 16:55:36');
insert into ORDERS VALUES (8,'c104',2,4,'2022-07-04 14:23:23');
insert into ORDERS VALUES (9,'c102',1,3,'2022-07-04 21:54:34');
insert into ORDERS VALUES (10,'c107',6,1,'2022-07-05 14:21:03');

--실습 1-4
SELECT * FROM Customer;
--실습 1-5
select CID, NAME, HP FROM CUSTOMER; 
--실습 1-6
select * from product;
--실습 1-7
select company from product;
--실습 1-8
select distinct company from product;
--실습 1-9
select pname,price from product;
--실습 1-10
select pname, price+500 as 조정단가 
from product;
--실습 1-11
select pname, stock, price 
from product 
where company = '오리온';
--실습 1-12
select ORD_PNO, ORD_CNT, ORD_DATE 
FROM ORDERS 
WHERE ORD_CID = 'c102';
--실습 1-13
SELECT ORD_PNO, ORD_CNT, ORD_DATE 
FROM ORDERS 
WHERE ORD_CID = 'c102';
--실습 1-14
SELECT * FROM PRODUCT 
WHERE PRICE >= 1000 AND PRICE <= 2000;
--실습 1-15
SELECT CID, NAME, HP, ADDRESS 
FROM CUSTOMER 
WHERE NAME LIKE '김%';

--실습 1-16
SELECT CID, NAME, HP, ADDRESS 
FROM CUSTOMER 
WHERE NAME LIKE '__';
--실습 1-17
SELECT * FROM CUSTOMER WHERE HP IS NULL;
--실습 1-18
SELECT * FROM CUSTOMER WHERE ADDRESS IS NOT NULL;
--실습 1-19
SELECT * FROM CUSTOMER ORDER BY RDATE DESC;
--실습 1-20
SELECT * FROM ORDERS 
where ORD_CNT >=3 
ORDER BY ORD_CNT DESC, ord_pno asc;
--실습 1-21
SELECT AVG(PRICE) FROM PRODUCT;
--실습 1-22
SELECT SUM(STOCK) AS "재고량 합계" 
FROM PRODUCT 
WHERE COMPANY = '농심';
--실습 1-23
SELECT COUNT(CID) AS 고객수 FROM CUSTOMER;
--실습 1-24
SELECT COUNT(distinct COMPANY) AS "제조업체 수" 
FROM PRODUCT;
--실습 1-25
SELECT ORD_PNO AS "주문 상품번호", 
    SUM(ORD_CNT) AS "총 주문 수량" 
FROM ORDERS
GROUP BY ORD_PNO
order by ORD_PNO asc;
--실습 1-26
SELECT COMPANY AS 제조업체, COUNT(*) AS 제품수, 
    MAX(PRICE) AS 최고가
FROM PRODUCT
group by company;
--실습 1-27
SELECT COMPANY AS 제조업체, COUNT(*) AS 제품수, 
    MAX(PRICE) AS 최고가
FROM PRODUCT
GROUP BY COMPANY
having count(STOCK) >=2;

--실습 1-28
SELECT ORD_PNO, ORD_CID, 
    SUM(ORD_CNT) AS "총 주문수량" 
FROM ORDERS
GROUP BY ORD_PNO, ORD_CID
order by ord_pno asc;

--실습 1-29check
SELECT ORD_CID, PNAME
FROM ORDERS a
join Product b 
on a.ord_pno = b.pno
WHERE ORD_CID = 'c102';

--실습 1-30check
select ORD_CID, NAME, PNAME, ORD_DATE
FROM ORDERS a
JOIN Customer b on a.ORD_CID = b.cid
JOIN Product c on a.ORD_PNO = c.pno
where ord_date like '2022-07-03%';
//where substr(ord_date, 1, 10) = '2022-07-03';